### ISSUE TITLE
Unable to connect to the graphic server error

### ISSUE THREAD

**Issue by defentos** [kalsan/proxmox-client#4]
Dear i keep getting the error message: Unable to connect to the graphic server error
i double checked my information, i'm using as hostname my local ip address as i would normally through the browser to access the proxmox gui
Any suggestion how to fix this?
![Screenshot_9](https://user-images.githubusercontent.com/82065872/113790472-b9c07b80-9741-11eb-814d-ca0ed54e92e8.png)

**Comment by kalsan** [comment]
Hi! From the message, I can deduce:
- proxmox-client successfully logs in to Proxmox and downloads the vv file
- remote-viewer is successfully started

Your problem is that the vv file does not appear to give you correct settings. It looks to me like the problem occurs after proxmox-client has completed, when virt-viewer attempts to connect to Proxmox itself.

Try to log in to your Proxmox web GUI and connect using Spice manually. The problem likeley occurs there as well.

Best
Kalsan

**Comment by defentos** [comment]
Hi Kalsan,

Foremost thank you for the quick reply.
The odd thing about this issue is i can connect to spice manually through the Proxmox web GUI without problems.
Spice/Proxmox downloads the vv file and opens in the viewer without any issues, so that's why i went to your github issues page in the hope maybe you might have an idea or solution.

Kind regards,
Defendos.

**Comment by kalsan** [comment]
Hi defentos,

Looks like you're in for some good-ol'fashionned debugging. Intercept the .vv file downloaded by proxmox-client and compare it to the one you download manually. Virt-Viewer consumes the file, thus you must use a breakpoint or return statement before virt-viewer is started.
The point behind this is that the differences in the files might indicate why it doesn't work.

Best,
Kalsan

**Comment by defentos** [comment]
Helo kalsan,

Intercepting the .vv file downloaded by the proxmox-client is easy enough gladly, but i dont understand what you mean by comparing it to the one downloaded manually, do you mean the file that your .jar program runs? if so how can i set up a breakpoint or return statement, i have zero knowledge about debugging sadly.
Would you mind guiding me in the right direction as i only have 1 .vv file at the moment which is from the proxmox-client
All other .vv files downloaded with your client are 0kb files in my temp folder.

Regards,
Defentos.

**Comment by kalsan** [comment]
Hi Defentos

So basically when you're in the Proxmox Web GUI and viewing a machine, there's a button on the top right which allows you to connect to that machine. One option is viewing the machine via VNC, but there's another that does so via SPICE. Use the latter and you'll get a .vv file.

proxmox-client basically logs in, downloads that file and starts virt-viewer which then establishes the graphical connection. When virt-viewer opens the file, it consumes it and the file is deleted.

Best,
Kalsan

**Comment by kalsan** [comment]
Hi defentos

Did this help? If so, the issue can be closed.

Best,
Kalsan

**Comment by arbrdev** [comment]
Hi!

The file is blank. I go to: "C:\Users\!user!\AppData\Local\Temp\remote-viewer1439377951253735658.vv" and the file has 0kbs.

Is normal this? I think the problem is the file dosn't have the required information to connect.

My command is:
java -jar proxmox-client.jar -h !ip! -p 8006 -u root -s !password! -r pam -c "C:\Program Files\VirtViewer v11.0-256\bin\remote-viewer.exe" -n proxmox1 -v 103

**Comment by arbrdev** [comment]
Ok! The problem was the IP. Change IP for "Fully qualified domain name", as you say in Usage, and it works!!! Thanks for your work @kalsan.

**Comment by kalsan** [comment]
That was effective self-help! Glad it worked for you and thanks for documenting your solution.

**Comment by KamikazeRaven** [comment]
Hi,

I am seeing this exact problem on windows 10 pro. It happened after a windows 10 update.

My virt-viewer version is: 11.0.256
I am able to download the .vv file and the .vv file has normal information. Nothing looks suspicious in it.

My firewall log does not show any traffic being blocked between windows 10 desktop and the PVE.
nmap scan from windows 10 to PVE also shows that port 3128 is open.

After days of Google search, this github issue resembles my issue closest and I could not find anything online that works on me.

Could you please give me some ideas on how to troubleshoot this issue?

**Comment by kalsan** [comment]
This Github repo is about a script that downloads a vv file from Proxmox. Further, you are hijacking a closed issue to ask for help for an unrelated problem. Please use Stackexchange or a forum for your question. This issue tracker is meant for discussion regarding proxmox-client.

**Comment by KamikazeRaven** [comment]
@kalsan sorry. I'll find another place.

**Comment by kalsan** [comment]
No problem. Good luck!
